// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package file_system

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/s3files"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/s3files/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/s3files-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.FileSystem{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetFileSystemOutput
	resp, err = rm.sdkapi.GetFileSystem(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetFileSystem", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.Bucket != nil {
		ko.Spec.Bucket = resp.Bucket
	} else {
		ko.Spec.Bucket = nil
	}
	if resp.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.CreationTime}
	} else {
		ko.Status.CreationTime = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.FileSystemArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.FileSystemArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.FileSystemId != nil {
		ko.Status.FileSystemID = resp.FileSystemId
	} else {
		ko.Status.FileSystemID = nil
	}
	if resp.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	if resp.Name != nil {
		ko.Status.Name = resp.Name
	} else {
		ko.Status.Name = nil
	}
	if resp.OwnerId != nil {
		ko.Status.OwnerID = resp.OwnerId
	} else {
		ko.Status.OwnerID = nil
	}
	if resp.Prefix != nil {
		ko.Spec.Prefix = resp.Prefix
	} else {
		ko.Spec.Prefix = nil
	}
	if resp.RoleArn != nil {
		ko.Spec.RoleARN = resp.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.StatusMessage != nil {
		ko.Status.StatusMessage = resp.StatusMessage
	} else {
		ko.Status.StatusMessage = nil
	}
	if resp.Tags != nil {
		f12 := []*svcapitypes.Tag{}
		for _, f12iter := range resp.Tags {
			f12elem := &svcapitypes.Tag{}
			if f12iter.Key != nil {
				f12elem.Key = f12iter.Key
			}
			if f12iter.Value != nil {
				f12elem.Value = f12iter.Value
			}
			f12 = append(f12, f12elem)
		}
		ko.Spec.Tags = f12
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)

	// --- Populate LifeCycleState from GetFileSystem response ---
	// The Status field in the API response conflicts with the Kubernetes
	// Status subresource, so it's in ignore.field_paths. We manually map
	// the LifeCycleState here from the resp variable (in scope from sdkFind).
	{
		lifecycleState := string(resp.Status)
		ko.Status.LifeCycleState = &lifecycleState
	}

	// --- Fetch FileSystemPolicy sub-resource ---
	if ko.Status.FileSystemID != nil {
		policyResp, policyErr := rm.sdkapi.GetFileSystemPolicy(ctx, &svcsdk.GetFileSystemPolicyInput{
			FileSystemId: ko.Status.FileSystemID,
		})
		rm.metrics.RecordAPICall("READ_ONE", "GetFileSystemPolicy", policyErr)
		if policyErr != nil {
			var apiErr smithy.APIError
			if errors.As(policyErr, &apiErr) && (apiErr.ErrorCode() == "ResourceNotFoundException" || apiErr.ErrorCode() == "ValidationException") {
				// ResourceNotFoundException: no policy exists.
				// ValidationException: file system is not yet available (e.g. still creating).
				// Both are expected — treat as empty policy.
				ko.Spec.Policy = nil
			} else {
				return nil, policyErr
			}
		} else if policyResp.Policy != nil {
			ko.Spec.Policy = policyResp.Policy
		} else {
			ko.Spec.Policy = nil
		}
	}

	// --- Fetch SynchronizationConfiguration sub-resource ---
	if ko.Status.FileSystemID != nil {
		syncResp, syncErr := rm.sdkapi.GetSynchronizationConfiguration(ctx, &svcsdk.GetSynchronizationConfigurationInput{
			FileSystemId: ko.Status.FileSystemID,
		})
		rm.metrics.RecordAPICall("READ_ONE", "GetSynchronizationConfiguration", syncErr)
		if syncErr != nil {
			var apiErr smithy.APIError
			if errors.As(syncErr, &apiErr) && (apiErr.ErrorCode() == "ResourceNotFoundException" || apiErr.ErrorCode() == "ValidationException") {
				// ResourceNotFoundException: no sync config exists.
				// ValidationException: file system is not yet available (e.g. still creating).
				// Both are expected — treat as empty configuration.
				ko.Spec.ImportDataRules = nil
				ko.Spec.ExpirationDataRules = nil
				ko.Status.LatestVersionNumber = nil
			} else {
				return nil, syncErr
			}
		} else {
			if syncResp.ImportDataRules != nil {
				rules := make([]*svcapitypes.ImportDataRule, len(syncResp.ImportDataRules))
				for i, r := range syncResp.ImportDataRules {
					rule := &svcapitypes.ImportDataRule{}
					if r.Prefix != nil {
						rule.Prefix = r.Prefix
					}
					if r.SizeLessThan != nil {
						rule.SizeLessThan = r.SizeLessThan
					}
					if r.Trigger != "" {
						trigger := string(r.Trigger)
						rule.Trigger = &trigger
					}
					rules[i] = rule
				}
				ko.Spec.ImportDataRules = rules
			} else {
				ko.Spec.ImportDataRules = nil
			}
			if syncResp.ExpirationDataRules != nil {
				rules := make([]*svcapitypes.ExpirationDataRule, len(syncResp.ExpirationDataRules))
				for i, r := range syncResp.ExpirationDataRules {
					rule := &svcapitypes.ExpirationDataRule{}
					if r.DaysAfterLastAccess != nil {
						d := int64(*r.DaysAfterLastAccess)
						rule.DaysAfterLastAccess = &d
					}
					rules[i] = rule
				}
				ko.Spec.ExpirationDataRules = rules
			} else {
				ko.Spec.ExpirationDataRules = nil
			}
			if syncResp.LatestVersionNumber != nil {
				v := int64(*syncResp.LatestVersionNumber)
				ko.Status.LatestVersionNumber = &v
			} else {
				ko.Status.LatestVersionNumber = nil
			}
		}
	}

	// --- Terminal condition on error lifecycle state ---
	if ko.Status.LifeCycleState != nil && *ko.Status.LifeCycleState == "error" {
		msg := "FileSystem is in error state"
		if ko.Status.StatusMessage != nil {
			msg = *ko.Status.StatusMessage
		}
		ackcondition.SetTerminal(&resource{ko}, corev1.ConditionTrue, &msg, nil)
	} else {
		ackcondition.SetTerminal(&resource{ko}, corev1.ConditionFalse, nil, nil)
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.FileSystemID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetFileSystemInput, error) {
	res := &svcsdk.GetFileSystemInput{}

	if r.ko.Status.FileSystemID != nil {
		res.FileSystemId = r.ko.Status.FileSystemID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateFileSystemOutput
	_ = resp
	resp, err = rm.sdkapi.CreateFileSystem(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateFileSystem", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.Bucket != nil {
		ko.Spec.Bucket = resp.Bucket
	} else {
		ko.Spec.Bucket = nil
	}
	if resp.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.CreationTime}
	} else {
		ko.Status.CreationTime = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.FileSystemArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.FileSystemArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.FileSystemId != nil {
		ko.Status.FileSystemID = resp.FileSystemId
	} else {
		ko.Status.FileSystemID = nil
	}
	if resp.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	if resp.Name != nil {
		ko.Status.Name = resp.Name
	} else {
		ko.Status.Name = nil
	}
	if resp.OwnerId != nil {
		ko.Status.OwnerID = resp.OwnerId
	} else {
		ko.Status.OwnerID = nil
	}
	if resp.Prefix != nil {
		ko.Spec.Prefix = resp.Prefix
	} else {
		ko.Spec.Prefix = nil
	}
	if resp.RoleArn != nil {
		ko.Spec.RoleARN = resp.RoleArn
	} else {
		ko.Spec.RoleARN = nil
	}
	if resp.StatusMessage != nil {
		ko.Status.StatusMessage = resp.StatusMessage
	} else {
		ko.Status.StatusMessage = nil
	}
	if resp.Tags != nil {
		f10 := []*svcapitypes.Tag{}
		for _, f10iter := range resp.Tags {
			f10elem := &svcapitypes.Tag{}
			if f10iter.Key != nil {
				f10elem.Key = f10iter.Key
			}
			if f10iter.Value != nil {
				f10elem.Value = f10iter.Value
			}
			f10 = append(f10, f10elem)
		}
		ko.Spec.Tags = f10
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateFileSystemInput, error) {
	res := &svcsdk.CreateFileSystemInput{}

	if r.ko.Spec.AcceptBucketWarning != nil {
		res.AcceptBucketWarning = r.ko.Spec.AcceptBucketWarning
	}
	if r.ko.Spec.Bucket != nil {
		res.Bucket = r.ko.Spec.Bucket
	}
	if r.ko.Spec.KMSKeyID != nil {
		res.KmsKeyId = r.ko.Spec.KMSKeyID
	}
	if r.ko.Spec.Prefix != nil {
		res.Prefix = r.ko.Spec.Prefix
	}
	if r.ko.Spec.RoleARN != nil {
		res.RoleArn = r.ko.Spec.RoleARN
	}
	if r.ko.Spec.Tags != nil {
		f5 := []svcsdktypes.Tag{}
		for _, f5iter := range r.ko.Spec.Tags {
			f5elem := &svcsdktypes.Tag{}
			if f5iter.Key != nil {
				f5elem.Key = f5iter.Key
			}
			if f5iter.Value != nil {
				f5elem.Value = f5iter.Value
			}
			f5 = append(f5, *f5elem)
		}
		res.Tags = f5
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateFileSystem(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteFileSystemOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteFileSystem(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteFileSystem", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteFileSystemInput, error) {
	res := &svcsdk.DeleteFileSystemInput{}

	if r.ko.Status.FileSystemID != nil {
		res.FileSystemId = r.ko.Status.FileSystemID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.FileSystem,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"AccessDeniedException":
		return true
	default:
		return false
	}
}
