// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type IPAddressType string

const (
	IPAddressType_DUAL_STACK IPAddressType = "DUAL_STACK"
	IPAddressType_IPV4_ONLY  IPAddressType = "IPV4_ONLY"
	IPAddressType_IPV6_ONLY  IPAddressType = "IPV6_ONLY"
)

type ImportTrigger string

const (
	ImportTrigger_ON_DIRECTORY_FIRST_ACCESS ImportTrigger = "ON_DIRECTORY_FIRST_ACCESS"
	ImportTrigger_ON_FILE_ACCESS            ImportTrigger = "ON_FILE_ACCESS"
)

type LifeCycleState string

const (
	LifeCycleState_available LifeCycleState = "available"
	LifeCycleState_creating  LifeCycleState = "creating"
	LifeCycleState_deleted   LifeCycleState = "deleted"
	LifeCycleState_deleting  LifeCycleState = "deleting"
	LifeCycleState_error     LifeCycleState = "error"
	LifeCycleState_updating  LifeCycleState = "updating"
)
