// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FileSystemSpec defines the desired state of FileSystem.
type FileSystemSpec struct {

	// Set to true to acknowledge and accept any warnings about the bucket configuration.
	// If not specified, the operation may fail if there are bucket configuration
	// warnings.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	AcceptBucketWarning *bool `json:"acceptBucketWarning,omitempty"`
	// The Amazon Resource Name (ARN) of the S3 bucket that will be accessible through
	// the file system. The bucket must exist and be in the same Amazon Web Services
	// Region as the file system.
	//
	// Regex Pattern: `^(arn:aws[a-zA-Z0-9-]*:s3:::.+)$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Bucket *string `json:"bucket"`
	// An array of expiration data rules that control when cached data expires from
	// the file system.
	ExpirationDataRules []*ExpirationDataRule `json:"expirationDataRules,omitempty"`
	// An array of import data rules that control how data is imported from S3 into
	// the file system.
	ImportDataRules []*ImportDataRule `json:"importDataRules,omitempty"`
	// The ARN, key ID, or alias of the KMS key to use for encryption. If not specified,
	// the service uses a service-owned key for encryption. You can specify a KMS
	// key using the following formats: key ID, ARN, key alias, or key alias ARN.
	// If you use KmsKeyId, the file system will be encrypted.
	//
	// Regex Pattern: `^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|mrk-[0-9a-f]{32}|alias/[a-zA-Z0-9/_-]+|(arn:aws[-a-z]*:kms:[a-z0-9-]+:\d{12}:((key/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(key/mrk-[0-9a-f]{32})|(alias/[a-zA-Z0-9/_-]+))))$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	KMSKeyID *string `json:"kmsKeyID,omitempty"`
	Policy   *string `json:"policy,omitempty"`
	// An optional prefix within the S3 bucket to scope the file system access.
	// If specified, the file system provides access only to objects with keys that
	// begin with this prefix. If not specified, the file system provides access
	// to the entire bucket.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	Prefix *string `json:"prefix,omitempty"`
	// The ARN of the IAM role that grants the S3 Files service permission to read
	// and write data between the file system and the S3 bucket. This role must
	// have the necessary permissions to access the specified bucket and prefix.
	//
	// Regex Pattern: `^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	RoleARN *string `json:"roleARN"`
	// An array of key-value pairs to apply as tags to the file system resource.
	// Each tag is a user-defined key-value pair. You can use tags to categorize
	// and manage your file systems. Each key must be unique for the resource.
	Tags []*Tag `json:"tags,omitempty"`
}

// FileSystemStatus defines the observed state of FileSystem
type FileSystemStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The time when the file system was created, in seconds since 1970-01-01T00:00:00Z
	// (Unix epoch time).
	// +kubebuilder:validation:Optional
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	// The Amazon Resource Name (ARN) of the file system.
	//
	// Regex Pattern: `^(arn:aws[-a-z]*:s3files:[0-9a-z-:]+:file-system/fs-[0-9a-f]{17,40})$`
	// +kubebuilder:validation:Optional
	FileSystemARN *string `json:"fileSystemARN,omitempty"`
	// The ID of the file system, assigned by S3 Files. This ID is used to reference
	// the file system in subsequent API calls.
	//
	// Regex Pattern: `^(arn:aws[-a-z]*:s3files:[0-9a-z-:]+:file-system/fs-[0-9a-f]{17,40}|fs-[0-9a-f]{17,40})$`
	// +kubebuilder:validation:Optional
	FileSystemID *string `json:"fileSystemID,omitempty"`
	// The version number of the synchronization configuration. Use this value with
	// PutSynchronizationConfiguration to ensure optimistic concurrency control.
	// +kubebuilder:validation:Optional
	LatestVersionNumber *int64 `json:"latestVersionNumber,omitempty"`
	// +kubebuilder:validation:Optional
	LifeCycleState *string `json:"lifeCycleState,omitempty"`
	// The name of the file system, derived from the Name tag if present.
	//
	// Regex Pattern: `^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty"`
	// The Amazon Web Services account ID of the file system owner.
	//
	// Regex Pattern: `^(\d{12})|(\d{4}-{4}-\d{4})$`
	// +kubebuilder:validation:Optional
	OwnerID *string `json:"ownerID,omitempty"`
	// Additional information about the file system status. This field provides
	// more details when the status is ERROR, or during state transitions.
	// +kubebuilder:validation:Optional
	StatusMessage *string `json:"statusMessage,omitempty"`
}

// FileSystem is the Schema for the FileSystems API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="FILESYSTEMID",type=string,priority=0,JSONPath=`.status.fileSystemID`
// +kubebuilder:printcolumn:name="LIFECYCLE",type=string,priority=0,JSONPath=`.status.lifeCycleState`
// +kubebuilder:printcolumn:name="BUCKET",type=string,priority=0,JSONPath=`.spec.bucket`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
type FileSystem struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FileSystemSpec   `json:"spec,omitempty"`
	Status            FileSystemStatus `json:"status,omitempty"`
}

// FileSystemList contains a list of FileSystem
// +kubebuilder:object:root=true
type FileSystemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FileSystem `json:"items"`
}

func init() {
	SchemeBuilder.Register(&FileSystem{}, &FileSystemList{})
}
