// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Specifies a rule that controls when cached data expires from the file system
// based on last access time.
type ExpirationDataRule struct {
	DaysAfterLastAccess *int64 `json:"daysAfterLastAccess,omitempty"`
}

// Specifies a rule that controls how data is imported from S3 into the file
// system.
type ImportDataRule struct {
	Prefix       *string `json:"prefix,omitempty"`
	SizeLessThan *int64  `json:"sizeLessThan,omitempty"`
	Trigger      *string `json:"trigger,omitempty"`
}

// Contains information about an S3 File System Access Point returned in list
// operations.
type ListAccessPointsDescription struct {
	FileSystemID *string `json:"fileSystemID,omitempty"`
	Name         *string `json:"name,omitempty"`
	OwnerID      *string `json:"ownerID,omitempty"`
	Status       *string `json:"status,omitempty"`
}

// Contains information about an S3 File System returned in list operations.
type ListFileSystemsDescription struct {
	Bucket        *string      `json:"bucket,omitempty"`
	CreationTime  *metav1.Time `json:"creationTime,omitempty"`
	FileSystemARN *string      `json:"fileSystemARN,omitempty"`
	FileSystemID  *string      `json:"fileSystemID,omitempty"`
	Name          *string      `json:"name,omitempty"`
	OwnerID       *string      `json:"ownerID,omitempty"`
	RoleARN       *string      `json:"roleARN,omitempty"`
	Status        *string      `json:"status,omitempty"`
	StatusMessage *string      `json:"statusMessage,omitempty"`
}

// Contains information about a mount target returned in list operations.
type ListMountTargetsDescription struct {
	FileSystemID  *string `json:"fileSystemID,omitempty"`
	OwnerID       *string `json:"ownerID,omitempty"`
	Status        *string `json:"status,omitempty"`
	StatusMessage *string `json:"statusMessage,omitempty"`
}

// A key-value pair for resource tagging.
type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}
